/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-06-25 15:07:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <br><br>\r\n");
      out.write("        <div class=\"innerOuter\">\r\n");
      out.write("            <h2>마이페이지</h2>\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("            <form action=\"update.do\" method=\"post\">\r\n");
      out.write("                <div class=\"form-group my-info\">\r\n");
      out.write("                    <label for=\"userId\">* ID : </label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"userId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"userId\" readonly> <br>\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"userName\">* Name : </label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"userName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"userName\" required> <br>\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"email\"> &nbsp; Email : </label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"email\"> <br>\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"age\"> &nbsp; Age : </label>\r\n");
      out.write("                    <input type=\"number\" class=\"form-control\" id=\"age\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.age }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"age\"> <br>\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"phone\"> &nbsp; Phone : </label>\r\n");
      out.write("                    <input type=\"tel\" class=\"form-control\" id=\"phone\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.phone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"phone\"> <br>\r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"address\"> &nbsp; Address : </label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"address\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.address }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"address\"> <br>\r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"\"> &nbsp; Gender : </label> &nbsp;&nbsp;\r\n");
      out.write("                    <input type=\"radio\" id=\"Male\" value=\"M\" name=\"gender\">\r\n");
      out.write("                    <label for=\"Male\">남자</label> &nbsp;&nbsp;\r\n");
      out.write("                    <input type=\"radio\" id=\"Female\" value=\"F\" name=\"gender\">\r\n");
      out.write("                    <label for=\"Female\">여자</label> &nbsp;&nbsp;\r\n");
      out.write("                    \r\n");
      out.write("                    <script>\r\n");
      out.write("                    	window.onload = () => {\r\n");
      out.write("                    		\r\n");
      out.write("                    		//javascript\r\n");
      out.write("                    		//document.querySelector('input[value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.gender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("]').checked = true;\r\n");
      out.write("                    		\r\n");
      out.write("                    	}\r\n");
      out.write("                    	//jQuery\r\n");
      out.write("                    	$(() => {\r\n");
      out.write("                    		$('input[value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.gender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("]').attr('checked', true);\r\n");
      out.write("                    	})\r\n");
      out.write("                    </script>\r\n");
      out.write("                </div> \r\n");
      out.write("                <br>\r\n");
      out.write("                <div class=\"btns\" align=\"center\">\r\n");
      out.write("                	<button type=\"button\" class=\"btn btn-dark\" data-toggle=\"modal\" data-target=\"#passwordForm\" style=\"float:left\">비밀번호 변경</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\" style=\"float:right\">수정하기</button>\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-danger\" data-toggle=\"modal\" data-target=\"#deleteForm\" style=\"float:right; margin-right:10px;\">회원탈퇴</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br><br>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 회원탈퇴 버튼 클릭 시 보여질 Modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"deleteForm\">\r\n");
      out.write("        <div class=\"modal-dialog modal-sm\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Modal Header -->\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h4 class=\"modal-title\">회원탈퇴</h4>\r\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <form action=\"delete.do\" method=\"post\">\r\n");
      out.write("                	<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"userId\"/>\r\n");
      out.write("                    <!-- Modal body -->\r\n");
      out.write("                    <div class=\"modal-body\">\r\n");
      out.write("                        <div align=\"center\">\r\n");
      out.write("                            탈퇴 후 복구가 불가능합니다. <br>\r\n");
      out.write("                            정말로 탈퇴 하시겠습니까? <br>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                            <label for=\"userPwd\" class=\"mr-sm-2\">Password : </label>\r\n");
      out.write("                            <input type=\"password\" class=\"form-control mb-2 mr-sm-2\" placeholder=\"Enter Password\" id=\"userPwd\" name=\"userPwd\"> <br>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Modal footer -->\r\n");
      out.write("                    <div class=\"modal-footer\" align=\"center\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-danger\" onclick=\"return deletePrompt();\">탈퇴하기</button>\r\n");
      out.write("                        <!-- 내가 작성한 이벤트(onclick)은 기존 이벤트보다 먼저 실행됨 -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("                <script>\r\n");
      out.write("                	function deletePrompt() {\r\n");
      out.write("                		//prompt() => input 요소에 입력된 값 반환 / 입력값 없으면 빈 문자열 반환 / 취소하면 null 반환\r\n");
      out.write("                		return prompt('회원탈퇴를 위해 \"회원탈퇴\"를 정확히 입력해주세요.') === '회원탈퇴' ? true : false;\r\n");
      out.write("                	}\r\n");
      out.write("                </script>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 비밀번호 변경 버튼 클릭 시 보여질 Modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"passwordForm\">\r\n");
      out.write("        <div class=\"modal-dialog modal-sm\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Modal Header -->\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h4 class=\"modal-title\">비밀번호 변경</h4>\r\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                    <!-- Modal body -->\r\n");
      out.write("                    <div class=\"modal-body pass-form\">\r\n");
      out.write("                            <label for=\"userPwd\" class=\"mr-sm-2\">기존 비밀번호 : </label>\r\n");
      out.write("                            <input type=\"password\" class=\"form-control mb-2 mr-sm-2\" placeholder=\"기존 비밀번호 입력\" id=\"userPwd\" name=\"userPwd\"> <br>\r\n");
      out.write("                            <label for=\"userPwd\" class=\"mr-sm-2\">변경 비밀번호 : </label>\r\n");
      out.write("                            <input type=\"password\" class=\"form-control mb-2 mr-sm-2\" placeholder=\"변경할 비밀번호 입력\" id=\"changePwd\" name=\"changePwd\"> <br>\r\n");
      out.write("                            <label for=\"userPwd\" class=\"mr-sm-2\">변경 비밀번호 확인 : </label>\r\n");
      out.write("                            <input type=\"password\" class=\"form-control mb-2 mr-sm-2\" placeholder=\"비밀번호 확인\" id=\"checkPwd\" name=\"checkPwd\"> <br>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Modal footer -->\r\n");
      out.write("                    <div class=\"modal-footer\" align=\"center\">\r\n");
      out.write("                    	<div align=\"center\" style=\"display:none;\" id=\"check-msg\">\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-danger\" disabled>변경하기</button>\r\n");
      out.write("                        <!-- 내가 작성한 이벤트(onclick)은 기존 이벤트보다 먼저 실행됨 -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                <script>\r\n");
      out.write("                $(() => {\r\n");
      out.write("                	const $userId = $('.my-info #userId');\r\n");
      out.write("            		const $userPwd = $('.pass-form #userPwd');\r\n");
      out.write("            		const $changePwd = $('#changePwd');\r\n");
      out.write("            		const $checkPwd = $('#checkPwd');\r\n");
      out.write("            		const $changeBtn = $('.modal-footer button[type=button]');\r\n");
      out.write("            		\r\n");
      out.write("            		\r\n");
      out.write("            		$checkPwd.keyup(() => {\r\n");
      out.write("            			if($changePwd.val() === $checkPwd.val()) { //비밀번호 확인이 일치하는 경우\r\n");
      out.write("            				\r\n");
      out.write("            				$changeBtn.attr('disabled', false);\r\n");
      out.write("            				$('#check-msg').hide();\r\n");
      out.write("            		\r\n");
      out.write("                		} else { //비밀번호 확인이 일치하지 않는 경우\r\n");
      out.write("                			\r\n");
      out.write("                			$('#check-msg').show().html('변경할 비밀번호를 다시 확인해주세요.<br>');\r\n");
      out.write("                			$changeBtn.attr('disabled', true);\r\n");
      out.write("                			\r\n");
      out.write("                		}\r\n");
      out.write("            			\r\n");
      out.write("            		});\r\n");
      out.write("            		\r\n");
      out.write("            		$changeBtn.click(() => {\r\n");
      out.write("            			console.log('ajax 실행');\r\n");
      out.write("                    	$.ajax({\r\n");
      out.write("                        	url:'change-pwd',\r\n");
      out.write("                        	type:'post',\r\n");
      out.write("                        	data:{\r\n");
      out.write("                        		userId : $userId.val(),\r\n");
      out.write("                        		userPwd : $userPwd.val(),\r\n");
      out.write("                        		changePwd : $changePwd.val()},\r\n");
      out.write("                        	success:(response) => {\r\n");
      out.write("                        		if(response === \"Y\") {\r\n");
      out.write("                        			alert('비밀번호가 변경되었습니다. 다시 로그인 해주세요.');\r\n");
      out.write("                        			location.href = 'logout.do';\r\n");
      out.write("                        		} else if(response === \"WrongPwd\") {\r\n");
      out.write("                        			$('#check-msg').show().html('기존 비밀번호가 올바르지 않습니다.<br>');\r\n");
      out.write("                        		} else {\r\n");
      out.write("                        			alert('비밀번호 변경 중 오류가 발생했습니다. 다시 시도해주세요.');\r\n");
      out.write("                        		}},\r\n");
      out.write("                        	error : () => {\r\n");
      out.write("                        		alert('비밀번호 변경 중 오류가 발생했습니다. 다시 시도해주세요.');\r\n");
      out.write("                        	}\r\n");
      out.write("                        });\r\n");
      out.write("                   });\r\n");
      out.write("            		\r\n");
      out.write("                }); \r\n");
      out.write("                	\r\n");
      out.write("                \r\n");
      out.write("                </script>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
